### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BikashGuragai** [hikmat30ce/vitalsourcePrint#1]
[0827/015437.545:INFO:CONSOLE(13)] "Warning: Button prop `color="neutral"` has been deprecated and will be removed in a future release.", source: https://bookshelf.vitalsource.com/js/fraction-0471a79623.min.js

**Comment by hikmat30ce** [comment]
can you provide more details so that I can fix and push the changes

**Comment by hikmat30ce** [comment]
pass below args when running in command line

`--course <CourseName>
--email <email>
--password <password>
--title "Course Title"
--total_pages 133`

**Comment by JacobHepworth** [comment]
This is a problem with Vitalsource. They are using deprecated code on their website and it's showing up in the console.
![console log](https://user-images.githubusercontent.com/24429051/92634543-afb0ca00-f291-11ea-9b06-295d643d0400.png)

**Comment by hikmat30ce** [comment]
> This is a problem with Vitalsource. They are using deprecated code on their website and it's showing up in the console.
> ![console log](https://user-images.githubusercontent.com/24429051/92634543-afb0ca00-f291-11ea-9b06-295d643d0400.png)

so this is not actually an issue with the code
